### ISSUE TITLE
Saving issues reported

### ISSUE THREAD

**Issue by mattpass** [icecoder/ICEcoder#606]
Sometimes when saving there are JS issues which cause things to stop working.

Some info reported here:
https://groups.google.com/forum/#!topic/icecoder/Ze-aaKiyUM8

**Comment by mattpass** [comment]
Found that it was trying to collect error info from a response that may not have info and was erroring. Just needed a little adjustment to the error handling. Done and closed.

**Comment by edxtech** [comment]
Needs reopening.
The latest version of IceCoder v6
PHP 7.3
The exact same issue as being described here: https://groups.google.com/d/msg/icecoder/Ze-aaKiyUM8/AqUMDsF0AgAJ

This usually only happens on my larger files(>500 lines)

**Comment by mattpass** [comment]
Will reopen while I investigate.

**Comment by dinther** [comment]
Hi, I started to have saving issues since a few weeks. I am sure it is due to some change in the chrome browser as I have not updated Icecoder.

Icecoder stops saving after a few successful file save attempts. I have multiple files open in the editor.
I managed to capture the error in the console when the save attempt fails
[www.ships2career.com-1546470226216.log](https://github.com/icecoder/ICEcoder/files/2722331/www.ships2career.com-1546470226216.log)

A reload of the page makes the save function work again for a short while although I loose the last code edits. I really need a quick fix for this as I rely on the editor and I just can't work this way.

**Comment by mattpass** [comment]
The save system has changed a lot and should be stable now, even better in the dynamicPaths branch. I'll close this issue assuming it's OK now.

(If not, pls try the dynamicPaths branch and raise a new issue if problems, but hopefully trouble free from here on).
