### ISSUE TITLE
Bad CSRF token - ICEcoder 6 beta

### ISSUE THREAD

**Issue by Cass0wary** [icecoder/ICEcoder#680]
Bad CSRF token. Please report the error info at https://github.com/mattpass/ICEcoder so it can be fixed.

CSRF issue:
REQUEST: f2a10bc1940270d231e1f7715662ad42
SESSION: 88ac2b9774e91fa10553f0ba1f675c10
FILE: /ice6/lib/login.php
GET: array ( 'get' => 'code', 'csrf' => 'f2a10bc1940270d231e1f7715662ad42', )
POST: array ( )

**Comment by shimmyshine** [comment]
I got this error once I updated to the 6 beta, I attempted to refresh and it just gave me a 500 internal server error.  ICEcoder writes into an error log in the root of it's file system, if you go check that and get a "expecting )" or "expecting ," error then the link [Here](https://groups.google.com/forum/#!topic/icecoder/HrOPzby87Mw) is how I fixed it.

**Comment by GhostCyborg** [comment]
After updating I seem to also have gotten a CSRF error, and when going to "example.com/ICECoder/" i get a 500 error. What @shimmyshine said is true, and does solve the problem, the best thing to do is look at the log file "error-log.txt", and see where the problem is, and what it is missing. It mostly seems to be missing an ")" or ";", if you have multiple sites, or multiple users, you need to change them in those files too. Meaning "config-example_com.php" and "config-example_net.php", or/and "config-USER-example_com.php" Some files depend, for example in some files I didn't need to add a ")", and only needed to add a ";". I'd just check the error log, and keep refreshing until you no longer get an error.

**Comment by alanef** [comment]
In my case it was a missing comma , after "last10Files"

**Comment by mattpass** [comment]
Closing this as it was a comma missing, has been fixed.
