### ISSUE TITLE
no Data -Error. Help?

### ISSUE THREAD

**Issue by Hobolandjacob** [icecoder/ICEcoder#718]
When I try to access ICEcoder and log in, It prints no Datano Data twice on the screen. This error did not occur on my last hosting provider, I tried to give the file 777 permission's yet the problem is still occurring maybe some insight from people that understand this issue would be great.

**Comment by mattpass** [comment]
Hmmm, is this before you even try to open a file in ICEcoder? Eitherway, it that sounds like it's not able to pull in the contents of the file. Likely because of a strange server configuration re paths.

If it's when you try and open a file in ICEcoder - you could edit lib/config_settings.php within your ICEcoder dir on your server and change the value of fileDirResOutput to say 'object' (or 'both'):

https://github.com/mattpass/ICEcoder/blob/master/lib/settings-system-params.php#L10

Now when you try to open a file, it will output what it's trying to open in your dev console's tab and you may be able to spot what path issues you may have, to help resolve?

**Comment by Hobolandjacob** [comment]
Strange thing actually I went into lib-config-settings.php and all that shows there is no Data

**Comment by mattpass** [comment]
Hmmm, well that file is created when you setup ICEcoder for the first time. I'd suggest a fresh clone from GitHub and try setting things up again. If that produces the same result, I'd suggest looking at your servers document_root setting.

**Comment by Hobolandjacob** [comment]
Yeah happened again, Semi new to online hosting stuff do you perhaps know where I may find document_root settings? Here is a screenshot of my file tree if that may help.
![screen shot 2017-08-07 at 3 43 09 pm](https://user-images.githubusercontent.com/6453006/29044920-2baa9bb6-7b87-11e7-8af9-0df7f08aec13.png)

**Comment by mattpass** [comment]
It looks like you have things in the right dir so that's good and I assume you visit yourwebsite.com/ice to start ICEcoder so nothing standing out as wrong on your setup.

You could create a new docroot.php file in public_html containing:
```
<?php
echo $_SERVER['DOCUMENT_ROOT'];
?>
```
...and see what it shows when you visit yourwebsite.com/docroot.php. It should in your case show /home/jacobweb/public_html

**Comment by Hobolandjacob** [comment]
echos /home/jacobweb/public_html

**Comment by marcoczen** [comment]
@Hobolandjacob  - do you have any .htaccess file set ? Any redirect commands ?

**Comment by Hobolandjacob** [comment]
@marcoczen No .htaccess is present anywhere in the file system that I have created nor could I find one, As of redirect commands am not sure as I just say this account up but I highly doubt there is.

**Comment by mattpass** [comment]
ICEcoder uses 'fopen' to open files, write to them etc. So I wonder if this is disabled on your server?

You could try creating a file containing ```<?php phpinfo(); ?>``` and check that over. It may show that fopen is disabled and if you enable it then everything starts to work.

You may also want to display phpinfo details on your other server and compare the output of the 2 files to see if anything obvious jumps out as being different and maybe causing you can issue.

I'd bet it's due to fopen being disabled tho.

**Comment by sagentic** [comment]
Just as confirmation, this happened to me. ICEcoder was working great until I upgraded the server to PHP 7.1 due to fopen being turned off with the upgrade. By changing it to `Allow_url_fopen: On` everything works great again.

**Comment by mattpass** [comment]
@sagentic That seems like a highly likely reason for other people too, thanks for sharing and maybe I can add some error handling in to better check it's available to use and inform user if it's not.

**Comment by mattpass** [comment]
Added a check on `allow_url_fopen` and will inform user if not enabled.
