### ISSUE TITLE
Issue with updating from V.6 Beta to V.6

### ISSUE THREAD

**Issue by MatthewC** [icecoder/ICEcoder#725]
After clicking the "Update" button it said something along the lines of "Failed to retrieve ICEcoder zip". Now the root directory of ICEcoder is just showing files, wanted to ask what I should do before trying to update it manually.

Also wanted to mention that the following folders:

- farbtastic/
- images/
- lang/
- processes/
- lib/
- test/

are completely empty.

**Comment by mattpass** [comment]
Sounds like it got part way through updating. You should find the previous version of ICEcoder in it's tmp dir and should be able to move the files back. I'll look into improving the update process so it checks it can do everything before attempting to do anything.

**Comment by GhostCyborg** [comment]
I followed what you said, and recovered my ICEcoder files. Although now that I think about it, how would I updated ICEcoder?
I am currently in V 6.0 Beta.

**Comment by GhostCyborg** [comment]
Any update on handling the Issue @mattpass ?

**Comment by mattpass** [comment]
Haven't looked at making the improvement mentioned, but should be simple enough if someone were to get to it before myself, else I've earmarked for v6.1. Not fixed as yet tho.

**Comment by mattpass** [comment]
Oh, Happy New Year to you also @GhostCyborg :-)

**Comment by mattpass** [comment]
Updating is a non-trivial thing I've been tinkering with for last few years, mainly complicated by ever changing system and user settings. While I've made improvements to allow updates to happen with more flexibility, it's not easy to have it automated due to the varying possibilities with customisation and incompatibilities that may occur.

So for now, the update system is disabled and manual installs of new version required.

**Comment by MatthewC** [comment]
Shame, although I can see why :/
