### ISSUE TITLE
Root path not correct

### ISSUE THREAD

**Issue by peepsnet** [icecoder/ICEcoder#726]
I am on godaddy cpannel and I am having issues with icecoders root path feature. 

I have installed icecoder in an ADMIN area( just a subdomain I created)
install dir:  **/home/username/sub_domains/admin/icecoder**
I would like to be able to edit files from **/home/username/** and down

If I change the root dir to **/home/username** in settings I get this...

Root:
**/home/username/sub_domain/admin/** (Which is the web root of the subdomain admin.site.com)

ICEcoder root:
**/home/username/sub_domain/admin/home/username/**

and the file manager path appears correct...

and no files in the file manager. 

Where is my error??

**Comment by peepsnet** [comment]
It appears the **root path** settings is not absolute??

https://groups.google.com/forum/#!topic/icecoder/3Lm4np8nlvA

I posted a screenshot of the conversation here in case it is lost
![untitled](https://user-images.githubusercontent.com/7506132/32109697-6f0e973e-bb03-11e7-9fbe-7682f17f46de.png)

**Comment by mattpass** [comment]
There are 2 root settings here - $docRoot which is set in lib/config___settings.php and should remain as $_SERVER['DOCUMENT_ROOT']; - this relates to your top level wwwroot which for your subdomain sounds like - /home/username/sub_domain/admin/

The other is the path you set in ICEcoders Edit > Settings section which is relative, from $docRoot. It enables you to concentrate on a specific sub-dir so you can say set /blah if you want it's file manager to start from  /home/username/sub_domain/admin/blah

Note you can't traverse upwards to work with files at say /home/username because that is above your doc root and would be a web server restriction. Whatever PHP has rights to access is what ICEcoder can access. You could either setup your dir structure and wwwroots in a different way or create a symlink to /home/username perhaps?
