### ISSUE TITLE
Sorry! - problem with file requested

### ISSUE THREAD

**Issue by chadpriddle** [icecoder/ICEcoder#761]
Fresh install on Ubuntu 16.04 PHP 7.0, I set my permissions and everything looks good. I can dbl click the test.php and edit it no problem. I created a symlink to access my /var/www/website files. When I dbl click any of those files I get the "Sorry! - problem with file requested" Any suggestions? All of my files and directories are under the www-data group

**Comment by mattpass** [comment]
@chadpriddle from speaking to a handful of people who have had a similar issue over the years, the issue always seems to be due to a misconfig of the web server, regarding paths and/or the servers `DOCUMENT_ROOT` value.

To help debug your issue can change a setting in the `lib/___config-settings.php` file: `fileDirResOutput` which you can change to one of the values mentioned, eg `raw`. Now if you have your browsers dev tools open to Console tab and try double clicking a file again, it will output info about what it's attempting to open, including the paths.

Aside from debugging the path issue, if you want to specify your own absolute path instead of the servers `DOCUMENT_ROOT`, you can set the value for the `docRoot` param also in that config file.

Hope this helps!

**Comment by mattpass** [comment]
Closing this as it is likely server related. If you need to pls reopen.
