### ISSUE TITLE
New files (0 length) cannot save

### ISSUE THREAD

**Issue by yinchy** [icecoder/ICEcoder#775]
Hi,
I am new to ICE Coder.
When I use the Ice file manager to create a New File, it cannot save.

And error is reported on line 76 of the file-control-xhr.php file.
PHP Notice:  Undefined offset: 0 in /home/playklou/dev.playkloud.com/ice/lib/file-control-xhr.php on line 76

When I edit an existing non-zero file, the save function runs fine.

I have also done a test by creating a new empty (0 length) file from an external file manager. And similarly, any edits to the file does not save

**Comment by mattpass** [comment]
@yinchy thanks for the bug report and sorry for delay in replying.

The PHP notice you found I came across also and is now fixed (https://github.com/icecoder/ICEcoder/commit/3f99e02aac20ec7f8d7f1cfa3ec16f38b5ef2dd1#diff-8c435af4592bbcb4f3bef2024e5d43bb) so having the latest code from this repo sorts that. It's a different issue really re banned files.

It sounds like the save issue you're finding is due to permissions. ICEcoder is PHP based and it can only write files (0 length or with content, it shouldn't matter), if it has permissions to.

That means if you're creating a new file, the dir you're creating it in must allow PHP to do that. It'd be blocking it either because it's not got the right owner/group or not high enough permissions to write it. The same is true if you try to update an existing file, if the file isn't allowing PHP to write it.

Look at the permissions for the dir you're trying to save into or the file you're trying to update and you'll find a permissions problem.

A simple test to prove this is set permissions to 777 (read, write and execute available to anything), you'll now be able to save. However, setting it to 777 is seen as a security risk, so you'll want to maybe change the owner or group.

Explanation you may know/not know: Every dir or file on Linux has an owner and group, eg `root / root`. It's likely that your web server is `www-admin` or something similar. If the permissions are say `644` for the file, PHP is going to be denied, as `www-admin` doesn't own the file (root does), doesn't belong in a group (it's in the root group) and it doesn't have permissions to write it.

Changing the files ownership and group from root to whatever your web server is using, (eg www-admin) is the better way to go.

Hope that all makes sense. Look into `chown`, `chgrp` and `chmod` to give PHP enough rights to write the dir/file. It'll write to that dir/file if it's able to. :-)

**Comment by mattpass** [comment]
PS - if you set 777 on a dir and still can't write a new, blank file of 0 length, please let me know. I just tried though and it works fine. I suspect it's a permissions problem so hope the info above is useful.

**Comment by yinchy** [comment]
Hi Matt

Thanks for addressing the bug!
I will try the updated version

yinch
