### ISSUE TITLE
Requirements failure on version 7

### ISSUE THREAD

**Issue by j-robin-hunter** [icecoder/ICEcoder#780]
I am getting a failure at startup saying that I don't have a working PHP session. Odd thing is that version 6 doesn't have a data directory but version 7 seems to require one but it was not created by upgrade process.

**Comment by RGuerreroC** [comment]
I just did a fresh install and im having same fail. Did you find any solution?

**Comment by mattpass** [comment]
@j-robin-hunter thanks for the info. In version 7 we started storing everything regarding config, settings and backups in the new `data` dir (rather than in `backups` (now inside the new data dir in v7) and `lib`). Something seems to have gone wrong with the update process for you, so grabbing a new copy of ICEcoder from GitHub and a fresh install may be a good idea.

**Comment by mattpass** [comment]
Hopefully all is working here for you since moving from version 6 to 7 and a fresh install, so closing.
