### ISSUE TITLE
adding ../data/ to the settings file

### ISSUE THREAD

**Issue by Voo3** [icecoder/ICEcoder#794]
adds ../date/ at the beginning of the settings file, then it is displayed
`../data/../data/../data/../data/<?php
$ICEcoderUserSettings = array(
,`
I fixed it for 
'go-localhost-root'
`if (is_writeable("../data/".$settingsFile)) {
            if ($settingsContents != 0) {
		$fh = fopen("../data/".$settingsFile, 'w');
		fwrite($fh, "../data/".$settingsContents);
		fclose($fh);
            }`
but for ftp-manafer.php there are no ideas yet

**Comment by mattpass** [comment]
The problem was actually prefixing the settings contents with "../data":
`fwrite($fh, "../data/".$settingsContents);`

Should be `fwrite($fh, $settingsContents);`

Fixed this in https://github.com/icecoder/ICEcoder/commit/fe6eed2934128ec6057daa247538a3f13b5e7a99

Thanks for reporting the bug and starting to look into it.
