### ISSUE TITLE
"You don't appear to have a working php session"

### ISSUE THREAD

**Issue by CACGaming** [icecoder/ICEcoder#802]
I am trying to run ICEcoder and now that I got it set up to the extent I have it the page just reads "Requirements problem! You don't appear to have a working php session". I am running it with NGINX and on page load it says [this](https://pastebin.com/Sv0AbPhG). I am aware that is might be (and most likely is) a server configuration error but I am at a total loss for what to do next.

**Comment by mattpass** [comment]
The first couple of things I'd try - do you have any files at all in:
`/var/lib/php/sessions/`

If this folder doesn't exist, you'll likely need to look more into generally why PHP sessions aren't working with Nginx.

However, ICEcoder sets its own save path for PHP sessions and it could be because your server doesn't currently let you do that. You could try commenting out this line in ICEcoder:
https://github.com/icecoder/ICEcoder/blob/master/lib/settings-common.php#L31
...close all browser windows and try again.

**Comment by CACGaming** [comment]
After commenting the line it said it didn't have permission to a file. So I did chmod -R 775 (I thought I had already done this) to the recommended folders (lib/ data/ tmp/ plugins/) and that fixed that problem, however I can't find anything on letting the server use a different save path for php sessions.

**Comment by CACGaming** [comment]
Okay so second problem (idk if this should be in a different issue submission) I cannot make files/folders.
[29-Jan-2020 00:05:05 UTC] PHP Warning:  file_put_contents(/usr/share/nginx/html/usr/share/nginx/htm/data/index.php): failed to open stream: No such file or directory in /usr/share/nginx/html/lib/indexer.php on line 233
shows up in error.log

**Comment by mattpass** [comment]
> After commenting the line it said it didn't have permission to a file. So I did chmod -R 775 (I thought I had already done this) to the recommended folders (lib/ data/ tmp/ plugins/) and that fixed that problem, however I can't find anything on letting the server use a different save path for php sessions.

So it sounds like you didn't set the permissions on the dirs and doing that sorted things out. If you comment out the session save path line as you did, then it will fallback to using the default path on your server (defined in your servers php.ini file).

**Comment by mattpass** [comment]
> Okay so second problem (idk if this should be in a different issue submission) I cannot make files/folders.
> [29-Jan-2020 00:05:05 UTC] PHP Warning: file_put_contents(/usr/share/nginx/html/usr/share/nginx/htm/data/index.php): failed to open stream: No such file or directory in /usr/share/nginx/html/lib/indexer.php on line 233
> shows up in error.log
> 
> EDIT: I removed $ICEcoderDir from indexer.php line 233 and it started giving permission errors, to test I then did chmod -R 777 on the html directory and it allowed public writing to all the files/directories. (It seems to be using the wrong user?)

It seems like you don't have ICEcoder setup in a dir within the document root? Looking at this line: `/usr/share/nginx/html/usr/share/nginx/htm/data/index.php`, I would guess that `/usr/share/nginx/html/usr/share/nginx/htm` is your document root?

If you view ICEcoder at `whateveryourdomainis.com/ICEcoder` then the path should be:  `/usr/share/nginx/html/usr/share/nginx/htm/ICEcoder/data/index.php`. You likely have a problem because you've installed ICEcoder in the document root? That's the wrong thing to do and should be in a dir in the document root, not just within the document root, but in a dir.

You also don't need to remove $ICEcoderDir, there's no need to make any adjustments here.

If you're still stuck right now - try again afresh and follow the 3 setup steps mentioned on the right hand side of the webpage at https://icecoder.net/
