### ISSUE TITLE
Can´t set password / login - Test page not working

### ISSUE THREAD

**Issue by wassereimer86** [icecoder/ICEcoder#826]
I'm a little overwhelmed. I have the problem that I can't set a password. The test page does not work either. There I get in the errors

`(index):16 Uncaught TypeError: Cannot read property 'openFiles' of undefined
    at (index):16
(anonymous) @ (index):16
(index):35 Uncaught TypeError: Cannot read property 'openFiles' of undefined
    at Object.openFile ((index):35)
    at runTests ((index):29)
    at onload ((index):22)`

What am i doing wrong? I have a working WordPress installation running. The Webserver can´t be that wrong setup.

I hope somebody can help. Would really like to give this a try. Looks good.

**Comment by wassereimer86** [comment]
I downloaded the zip from Github. There was no test folder anymore. I made a fresh install. This time i set the password i noticed that the url was like domain.tld/folder////lib/login or somethingl like that. After i manually went to the main url i had the Login Prompt.

**Comment by mattpass** [comment]
If you have ICEcoder installed under the same document root that WordPress is under, maybe it has .htaccess rules that are causing strange behavior.

Have you tried installing under a different document root where nothing else will interfere?

**Comment by wassereimer86** [comment]
It has its own folder. More should not be necessary.

```
.../wordpress/
.../icecoder/
.../phpmyadmin/
```

Also i noticed that plugin installation seems to have problems when reloading to fast after pressing install. I install a plugin, reload and ..... its not there. Wait, reload .... still not there. Installing again, waiting a bit, reload. Working.

Also i have no warnings or errors when there is an error in the code like i have no closing bracket.

**Comment by mattpass** [comment]
A few things to cover here:

- test page - this wasn't working properly and so has been removed in this latest GitHub code as you've found.
- login/password - there is a bit of a glitch I've yet to get to the bottom of re this, but you were generally able to set a password and login, even if behavior was a bit unexpected? (Guess so as you mention a plugin installation issue.
- plugins - an issue here I didn't anticipate re trying to make plugins instantly available where possible, will investigate and sort.

Thanks for raising the issues.

**Comment by wassereimer86** [comment]
> * login/password - there is a bit of a glitch I've yet to get to the bottom of re this, but you were generally able to set a password and login, even if behavior was a bit unexpected? (Guess so as you mention a plugin installation issue.

Yes, it worked at the end. But only cause i saw, after about 40 tries, that the url is messed up. I still had the screen to setup a password. After i manually changed the url to the base one i got the login screen.

> * plugins - an issue here I didn't anticipate re trying to make plugins instantly available where possible, will investigate and sort.

Or just open a popup which says it is getting installed whith a progess bar so that the bacvkground prozess has the time it needs. You can control checkpoints if it is fully ready to check for specific files or something like that. Just an idea. But i dont know exactly how it works in your case.

**Comment by cedricgeffroy** [comment]
Hello, I confirm having the same issue with a fresh 7.0 install.

> I downloaded the zip from Github. There was no test folder anymore. I made a fresh install. This time i set the password i noticed that the url was like domain.tld/folder////lib/login or somethingl like that. After i manually went to the main url i had the Login Prompt.

If i'm logged out and go to domain.tld/icecoder, i'm redirected to 
domain.tld/icecoder//lib/login.php

But I'm able to login, then url is :
domain.tld/icecoder//

If I try to access domain.tld/icecoder when already logged in, I'm redirect to 
domain.tld/icecoder/
(no double slash at the end)

Also, probably because of this issue i'm unable to add local and remote git folders. 
after clicking on Add nothing happens local and remote paths inputs are emptied.
Then Icecoder is not responsible anymore and if I reload the page I'm prompted with set password / login and this url : 
domain.tld/icecoder///lib/login.php
(note the triple / )

Thank for this awesome tool anyway :)

**Comment by mattpass** [comment]
Thank you both for the reports and patience. ICEcoder has had a LOT of updates since you've both reported issues, which include covering the items mentioned:

- Old test system removed
- Setting password fixed
- Multiple ////'s on setup/login fixed
- Test page now part of requirements system
- Plugin install system fixed

I think all is working generally very well now - please try latest version and let me know if any of the above is still problem.

Will close this issue as I believe all is sorted here now.
