### ISSUE TITLE
Pull requests

### ISSUE THREAD

**Issue by atorresbr** [icecoder/ICEcoder#941]
Hello, I'm having trouble creating PR's ..

https://www.facebook.com/photo?fbid=1537014006499710&set=a.121994628001662

**Comment by mattpass** [comment]
@atorresbr your version of ICEcoder you're working on is very old (see https://github.com/atorresbr/ICEcoder/commits/master).

There's been a lot of updates since 4th Aug, including a massive restructure and code review. So trying to raise a PR based on an old fork which wants to merge into the latest version is showing many conflicts.

The best advice is probably to put a copy of your theme aside, take a fresh fork of ICEcoder and paste your theme into the fresh copy and raise a PR from that.

Then it'll show just the 1 file has changed, not hundreds of conflicts to resolve.

Hope that helps.

**Comment by mattpass** [comment]
Hi @atorresbr - your PR was much closer to what I'd expect, but you also had the **ICEcoder-master.zip** file within it and so there were 2 files, not 1 file containing your theme change. I closed your PR and added just the theme file change as you wanted.
