### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by Singman33** [icecoder/ICEcoder#951]
Hi,
I need to reset the password so I could submit another one. But how ?
Maybe removing a file or a parameter, but can"t find which.

**Comment by mattpass** [comment]
In ICEcoders `data` dir you'll find a `config-YOURDOMAINHERE.php` file. That's a PHP serialized data file. Open that in a text editor on your server and within it (about half way along the long line of serialized data) you can set the "password" length & value back to 0 and a blank string. ie:

`s:8:"password";s:0:"";`

It should look EXACTLY like that when you've set `s:0:""` instead of what you had previously.

Reload ICEcoder login page in your browser and now you can set a password.

**Comment by Singman33** [comment]
It doesn't work, showing me the password creation form but refusing anything I could enter (even the working original password).

**Comment by mattpass** [comment]
The domain based filename would be the one to amend really. It should work fine - you met all password strength rules?

I see you've raised another issue from a logged in point of view. Did you resolve this issue in the end?

**Comment by mattpass** [comment]
Will assume you resolved this issue and so closing.

**Comment by dewebmeester** [comment]
Unfortunately, doesn't work for me neither. After changing the mentioned file I see a login screen but not the create password screen.
![login-screen](https://user-images.githubusercontent.com/4035761/142649602-cfd5b997-2899-464a-8dc5-178578db5116.png)
Or is it possible to change settings to "enable registration" by changing any files? I am a teacher and have daily students with lost passwords so they are re-installing IceCoder in order to get access again. A simplier workaround would be helpfull. Kind regards, Meindert

**Comment by dewebmeester** [comment]
Aha, I found the solution. You should go to the config-global.php file and simply change "enableRegistration";b:0;s:9: to "enableRegistration";b:1;s:9:

**Comment by mattpass** [comment]
@dewebmeester yeah, previous info here is old and setting is in config-global.php as you mentioned. I'll look to add this as FAQ info on the website. 👍🏼
