### ISSUE TITLE
Freezing Tabs

### ISSUE THREAD

**Issue by raymondsalas** [icecoder/ICEcoder#966]
I am having instances where tabs do not immediately respond when clicked. Steps to reproduce:
Step 1: Open 4 files (I used PHP files)
Step 2: Close the **LAST** opened file
Step 3: Attempt to click the FIRST tab THEN the SECOND tab (it doesn't work in the first few clicks unless I use right-click)

**Comment by mattpass** [comment]
I see a similar bug - open 4, close 4th, click 1st (as much as you like), doesn't switch to 1st.

Click 2nd or 3rd and they work fine, then can click 1st fine thereafter.

**Comment by mattpass** [comment]
OK fixed. Was a weird "gotcha".

_Reason: when you move the mouse pointer over the close icon it sets `overCloseLink` to `true` (and `false` on mouse out). However, if you move the pointer over it, it's `true`, but when you click the close icon, the tab, along with the icon are removed, so there's never a mouse out event to set back to `false`. There's logic on tabs to ensure when you click them you're not over the close icon. Because it's still set to `true`, it thinks you are and so won't switch to the tab. It'll work if you move pointer over a close icon, out again and then click 1st tab._

All I needed to add was to add this https://github.com/icecoder/ICEcoder/commit/da88db20fb50f1c4c85cde577264fedb60973ff1#diff-b7e2909e0304b44a64d33f7c2111a2a2f9dfbb4a402c9a6f26d0adf3468d8f48R4515-R4516 when you close the tab to definitely set that boolean to `false`.

**Comment by raymondsalas** [comment]
Confirming that the fix worked. Thanks a lot, @mattpass !
