### ISSUE TITLE
Error when trying to switch to multi-user in ICEencoder 8.0 Beta

### ISSUE THREAD

**Issue by jenspr** [icecoder/ICEcoder#981]
I checked multi-user checkbox in the settings (did not check registration box).
When I logged out and tried to login again (I got prompted for User/PW)
I since get error and get refused to login.
This is what I receive

„ICEcoder echo SettingsClass->versionNp.?>
REQUIREMENTS PROBLEM!

Sorry, but ICEencoder has a problem running on your server:
You don’t seem to have the user config file:
Data/config-admin-jp01_de.php“

I can’t reverse. So I can’t login anymore.  I checked via FTP. The file mentioned is available on the server. 
I guess I have to reinstall from scratch?

Don't know if this is an issue or I did something wrong.

**Comment by mattpass** [comment]
@jenspr I'll see if I can reproduce the issue. In the meantime, in the `data` folder, delete any files that start `config`. This gives you a fresh start and reloading in the browser you can set a new password and get back in. No need for a full install, just a fresh start.

**Comment by mattpass** [comment]
That definitely is a UX problem! If you're a single user, you have no username, so if you switch to multi-user but no registration permitted, there's no possible username you could log in as. The error shown is then a knock on problem. 

Related issue to cover: #878 but will look into rolling out the first part initially (first user to login is "admin") - need to also note that on login page as the default user.

**Comment by jenspr** [comment]
Thanks for the quick help. 
Super!!

**Comment by mattpass** [comment]
No problems 👍🏼 ...have also pushed some updates in this commit https://github.com/icecoder/ICEcoder/commit/dcf1f50cf00746c54fd791a6c680410ac946acc4

It means now that 1st user is admin (rather than having no name), there's helpful UX re that, no wrong error message and shouldn't be able to lock yourself out anymore when switching from single user to multi user mode (as you have a username "admin" now, so login possible).
